//
//  BMConstant.h
//  Boom
//
//  Created by Boom on 10/06/14.
//  Copyright (c) 2014 Boom. All rights reserved.
//

#import <Foundation/Foundation.h>

#define kNO_NETWORK_AVAILABLE_MSG       @"No Network Available"
#define kNO_UNABLE_TO_REQUEST_MSG      @"Cannot connect to Boom. It may be down for maintenance or temprorarily unavailable. Please try again after sometime"
#define kAUTHEONTICATION_CHALLENGE_MSG  @"Authentication challenge received"
#define kERROR                          @"Error"
#define PROJECT_NAME                    @"Boom"
#define kREWARDED                       @"Rewarded"
#define kNOT_REWARDED                   @"Not Rewarded"
#define kNO_DATA                        @"No Data"
#define kDEBUG_DESCRIPTION              @"NSDebugDescription"

#define kVIDEOLOADING                   @"LD=Y"
#define kANNOTATION                     @"AN=Y"
#define kPLAYCOMPLETION                 @"TPB=Y"
#define kPLAYSTART                      @"PY=Y"
#define kPLAYEND                        @"CP=Y"
#define kPAUSEDTIME                     @"TM="
#define kWATCHTIME_CT                   @"ct="
#define kWATCHTIME_YTT                  @"ytt="
#define kWATCHTIME_TT                   @"tt="

#define KOFFERLIST_URL                  @"http://boom.boomvideo.tv/alpha/offerlist/assets/assets/index.html?boomid=kBoomGuid&countrycode=kCountryCodeId"
#define VPN_SERVER_URL                  @"http://180.92.199.171/MobileWS/GetCampaigns?publisherGUID=kGameGuid&OfferList=kOfferlistId&countrycode=kCountryCodeId&Preroll=kPrerolId&Reward=kRewardId"
#define kSURVEY_TRACKING_URL            @"http://content.boomvideo.tv/alpha2/ads/ads_track/tracking_mulsurvey.php?answer=kOption&ID=kGameGuid&type=0&qid=kQID&nextid=kNextQId&vpid=kVpidString"
#define kBRANDLIFT_TRACKING_URL         @"https://c.bvcau.com.au/alpha/boomsurvey/track_survey.php?ID=kGameGuid&vpid=kVpidString&val=kBrandLiftId&type=0"
#define kBRANDLIFT_LOADING_URL          @"https://c.bvcau.com.au/alpha2/ads/boomsurvey/track_survey.php?ID=kGameGuid&vpid=kVpidString&val=Loading&type=0"
#define kGAMEGUID                       @"kGameGuid"
#define kOFFERLISTID                    @"kOfferlistId"
#define kCOUNTRYCODE                    @"kCountryCodeId"
#define kPREROLLID                      @"kPrerolId"
#define kBRANDLIFTID                    @"kBrandLiftId"
#define kREWARDID                       @"kRewardId"
#define kQUESTIONID                     @"kQID"
#define kNEXTQUESTIONID                 @"kNextQId"
#define kOPTION                         @"kOption"
#define kPOST                           @"POST"
#define kGET                            @"GET"

#define kFACEBOOKSHARED                 @"FB=Y"
#define kTWITTERSHARED                  @"TW=Y"
#define kEMAILSHARED                    @"EM=Y"
#define kEMBEDSHARED                    @"embed=Y"
#define kGOOGLEPLUSSHARED               @"GP=Y"
#define kOPTIONID                       @"kOptionId"
#define kBOOMGUID                       @"kBoomGuid"
#define kSTATUSID                       @"kStatus"
#define kVPID                           @"kVpidString"
#define kID                             @"kDefault"
#define kNONVIDEOTYPE                   @"kNonVideoType"
#define kPLATFORM                       @"kPlatform"
#define kFRE                            @"kFre"
#define kCALLBACK                       @"kCallBack"

#define kTRACKING_LOADING_URL           @"https://content.boomvideo.tv/alpha2/ads/ads_track/loading.php?ID=kDefault&vpid=kVpidString&kStatus"
#define kTRACKING_URL                   @"https://content.boomvideo.tv/alpha2/ads/ads_track/tracking.php?ID=kDefault&vpid=kVpidString&kStatus"
#define kTRACKING_TM_URL                @"https://content.boomvideo.tv/alpha2/ads/ads_track/track_tm.php?ID=kDefault&vpid=kVpidString&kStatus"
#define kTRACKING_RULES_URL             @"https://content.boomvideo.tv/alpha2/ads/ads_track/tracking_rules.php?ID=kDefault&vpid=kVpidString&kStatus"
#define kTRACKING_LIKE_URL              @"https://content.boomvideo.tv/alpha2/ads/ads_track/track_like.php?ID=kDefault&vpid=kVpidString&kStatus"
#define kTRACKING_TAG_URL               @"https://content.boomvideo.tv/alpha2/ads/ads_track/tracking_tag.php?ID=kDefault&vpid=kVpidString&kStatus"
#define kOFFERLIST_TRACKING_TAG_URL     @"https://c.bvcau.com.au/alpha/ads/ads_track/tracking_tag.php?ID=kDefault&boomguid=kBoomGuid&type=kNonVideoType&vpid=kVpidString&platform=kPlatform&fre=kFre&callback=kCallBack"
#define kOFFERLIST_TRACKING_DEMOGRAPHIC_URL @"http://content.boomvideo.tv/alpha2/ads/boomsurvey/track_survey.php?ID=kDefault&vpid=kVpidString&val=kOptionId&type=kNonVideoType&pram=kStatus"

#define kGENERATE_VPID_URL               @"http://content.boomvideo.tv/alpha/ads_game/generatevpid.php?boomguid="

#define kFACEBOOK                       @"Facebook"
#define kTWITTER                        @"Twitter"
#define kGOOGLE                         @"Google+"

#define kVPID_REQUEST_TYPE              @"vpidRequest"
#define kSERVER_DATA_REQUEST_TYPE       @"serverDataRequest"
#define kANALYTICS_REQUEST              @"analyticsRequest"

#define kParse_id                       @"id"
#define kParse_guid                     @"guid"
#define kParse_sponserName              @"SponserName"
#define kParse_sponserLink              @"SponserLink"
#define kParse_sponser                  @"sponser"
#define kParse_playerLink               @"playerlink"
#define kParse_gameCampaignGuid         @"GameCampaignGUID"
#define kParse_annotationLink           @"AnnotationLink"
#define kParse_annotationTitle          @"AnnotationTitle"
#define kParse_annotationStartTime      @"AnnotationStartTime"
#define kParse_annotationFinishTime     @"AnnotationFinishTime"
#define kParse_videolink                @"videolink"
#define kParse_youtubeId                @"YoutubeId"
#define kParse_callbackurl              @"callbackurl"
#define kParse_youtubeLink              @"YoutubeLink"
#define kParse_completedTrackingPixel   @"CompletedTrackingPixel"
#define kParse_currency                 @"currency"
#define kParse_description              @"Description"
#define kParse_height                   @"height"
#define kParse_imgThumbnail             @"ImgThumbnail"
#define kParse_mobileDescription        @"MobileDescription"
#define kParse_name                     @"Name"
#define kParse_nonVideoCampaign_AndroidUrl @"NonVideoCampaign_AndroidUrl"
#define kParse_nonVideoCampaign_Description @"NonVideoCampaign_Description"
#define kParse_nonVideoCampaign_ImgThumbnail @"NonVideoCampaign_ImgThumbnail"
#define kParse_nonVideoCampaign_IOSUrl @"NonVideoCampaign_IOSUrl"
#define kParse_nonVideoCampaign_Name    @"NonVideoCampaign_Name"
#define kParse_nonVideoCampaign_Type    @"NonVideoCampaign_Type"
#define kParse_nonVideoCampaign_WebSiteUrl @"NonVideoCampaign_WebSiteUrl"
#define kParse_preroll                  @"preroll"
#define kParse_privatekey               @"privatekey"
#define kParse_reward                   @"reward"
#define kParse_skip                     @"skip"
#define kParse_title                    @"Title"
#define kParse_trackingPixel            @"TrackingPixel"
#define kParse_value                    @"value"
#define kParse_width                    @"width"
#define kParse_skiptime                 @"skiptime"
#define kParse_callbackfiretime         @"callbackfiretime"
#define kParse_socialSharing            @"SocialSharing"
#define kParse_DefaultSkipTime          @"10"
#define kParse_DefaultCallBackFireTime  @"20"
#define kParse_gamecampaigid            @"gamecampaigid"
#define kParse_text                     @"text"
#define kParse_optionId                 @"OptionId"
#define kParse_brandLiftId              @"BrandLiftId"
#define kParse_Option                   @"Option"
#define kParse_survey                   @"Survey"
#define kParse_QuestionId               @"QuestionId"
#define kParse_VideoCampaignId          @"VideoCampaignId"

#define kAnalytics_CallBack_NoData      @"NoData"
#define kAnalytics_CallBack_EventName   @"eventName"
#define kAnalytics_CallBack_VideoCompleted @"videoCompleted"
#define kAnalytics_CallBack_VideoCompletedWithPercent @"VideoCompletedWithPercent"
#define kAnalytics_CallBack_VideoPercent @"videoPercentage"
#define kAnalytics_CallBack_VideoStart  @"videoPlayStart"
#define kAnalytics_CallBack_VideoCompletedAsRule @"videoCompletedAsPerRule"
#define kAnalytics_CallBack_Points      @"pointsRevealed"
#define kAnalytics_CallBack_NoPoints    @"NoPoints"
#define kAnalytics_CallBack_NetworkNotAvailable @"networkNotAvailable"
#define kAnalytics_CallBack_SurveyNotCompleted @"SurveyNotCompleted"
#define kAnalytics_CallBack_surveyNotCompleted @"surveyNotCompleted"
#define kAnalytics_CallBack_surveyCompleted    @"surveyCompleted"
#define kAnalytics_CallBack_survey             @"Survey"
#define kAnalytics_CallBack_Redirected_Blog     @"redirectedToBlog"
#define kAnalytics_CallBack_Redirected_Instagram @"redirectedToInstagram"
#define kAnalytics_CallBack_Redirected_SlideShare @"redirectedToSlideshare"
#define kAnalytics_CallBack_Redirected_Installation @"redirectedToInstallation"
#define kAnalytics_CallBack_Redirected_Annotation @"redirectedToAnnotation"
#define kAnalytics_CallBack_Posted_Facebook     @"linkPostedOnFacebook"
#define kAnalytics_CallBack_Posted_Twitter      @"linkPostedOnTwitter"
#define kAnalytics_CallBack_Posted_GooglePlus   @"linkPostedOnG+"
#define kAnalytics_CallBack_Posted_Email
#define kAnalytics_CallBack_Posted_Embed
#define kAnalytics_CallBack_Blog                @"Blog"
#define kAnalytics_CallBack_Instagram           @"Instagram"
#define kAnalytics_CallBack_Slideshare          @"SlideShare"
#define kAnalytics_CallBack_Installation        @"Install"
#define kAnalytics_CallBack_Purchase            @"Purchase"
#define kAnalytics_CallBack_Website             @"Website"
#define kAnalytics_CallBack_VideoPaused         @"videoPaused"

#define kUserDefaultObject              @"YES"
#define kBundleFile                     @"boomVideoSharingData"
#define kPlistType                      @"plist"
#define kGoogleClientId                 @"googlePlusClientId"

#define kTWITTER_ERROR                   @"Twitter Error"
#define kTWITTER_ERROR_MESSAGE           @"You may not have set up Twitter service on your device. Please set up your Twitter account in Settings of the device."
#define kFACEBOOK_ERROR                  @"Facebook Error"
#define kFACEBOOK_ERROR_MESSAGE          @"You may not have set up Facebook service on your device. Please set up your Facebook account in Settings of the device."

#define kCLOSE_ICON                     @"iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAABIAAAASABGyWs+AAAACXZwQWcAAABAAAAAQADq8/hgAAAMeElEQVR42u2af4xc1XXHP+fe+96b37O7s7u22d0aAUFVEHZqKAURGgvMQutg01ZEgGhJm1IEblTyw4IGSMSvVhERRKWmAhI1TlJAVBXGa5JCMQKBFEGxY4NSUWJ+OCz457K/vDs78967p3/MrmPiH+yOB1Qp+5WuNBq9Oe98v/fcc+85d2Ae85jHPOYxj3nMYx6/nZBWGXrF9QNgEQywNHmqpY5udxfhgRQF4Mzk6ZbYNa0wssX1s5sqS2njZwyxnzqvu5UtI/+6W8l+6vyMIZbSxm6qbJkW/P+FAAArWSJvM5G/jnPMJGnLyM9gkpTrOMe8zUR+JUtaFrnHZWiLvRABYqO9VfWrErQfmHDI+jOChZvfrA+livJ7aXPh+nPbjyCcHFbslnj3BQl6NZB3yNNZMRsDL4MKnJH+1ycvwCv2QrJYJkhOCLGXq3C1whJQBDYYlYcS/DMBpp42IcLPbT8WIcaHDrPCi16jcCkIAq+Ksr5O+mge936VlDObFKEpAbbaC6nhTYRtE/iLDPbLBdxJZQlIUIa1ziTpcyl6M7C1KjoVqbJslk5utRdSEyGrkgGWWeSuHHZ5u4Q4hFGNOUDy1hTpfQo/rJGORBg/W/uHwjUlG2CQLoErQuyNJQm6ygRksI0cLYJQP3dc43UKa0LlZSCZi/1QccAygXV5cae1EVLEIYARwSCLvXJjnRSDPALsaYbHnCLgzenMvkeri7O4L0SYvy5JcGqJgCy2EZw0tqoDJIxQTyc0eSHB352QPGUJUkWPGq6v2AsRhJTYOtxFDrM2L+68NkJbwGGn7StKlZQxYsY0fqOG/16V5LEFkt0JcHLy5Kw5zSkCangDVEqEf+qQq7LYU0vTMw/gp/doi5DHooTWo8urMOpxKDwDUn/J9vMHv5ETXrL90+QIDW6Fw/xNFru8TEgei0UO2hc4+M4UPdWQXhVgkhr+x8AQ4D8WAXLYADhHhS+GmCV5HNF02Oshz6UogpDHoQJea6s9Wk7REUW2jkgw9bLt56xpEV62/QxLQEXjjKDLLLI2wi5vk4j8dNinh7xh5lOEpSwhjmRJHf9FgTeBp4DaxyJAp4YBcCbWtIs0At6neszf5LGohAicO67xOmBNUZPDckJREwcsA9blptd8HgvoMacztJYAi6q2k/ozgWc/NgFsLlPDms2mu3y+ivTpxBS6bwySFOTwdCLTI9cI/0CF0w9ocpfF3x0SPfWf9g9TgJDQKrV+QdYWJDi9TGhz0zMPH46ug1AFZ5GuEiafQVR/5feObib1NcbnwGkuAtxZe9UbF+5K942E5KIessFC6gkaJ5D6w0SYWRqWmRpBTIKeqGhhinjkDcbfHSV2FdyKEHNtFntxu4Qmj8Mh+GORDyzSnkd6K0h7YTvthfXhX/U/EQz8fXzbbbfNmtPckuBZN4JQT5csftDsGx0nG96F10WA1eFxOMpySA+JBC8wrPXVKVr4FIWJhhPytQh7QZuE5I6w5g/3WpC2PPRWUjqKuzRy9/iu8iP8+wsxj70wF0rN1QJTN10ag2xQI2uoFN+nr4JWSngUr0cfqJJXSxsBedzZBdwPCrgf5HFntxGQVwt6bBseRSsl6KtApfi+GlkDsqHh09zR1EmwuvJOBE9qbEnQS3Uq/qofmViq7w2h+4+eE2ZemeKp4alPp7cQQ4TBYuBoMz+z5jtLSE8F05bfLpngHkU2WJ+OKYbsk7d8MgIATF7yD0iSUg0IQ7HX6GTtGh05sNS/ux8dnoA4OaoIv5ncjpnsZsgHDmnPY/o6kbbCdslFD9U1fSgbU1dnyQ18oykex1UNHlh5B6CkVgKjcgX19C4/NLrIDw5Z/eDoOWHOsIJ0FDG9ldRUyrsI7c1e9BGbagxC4clbmzbddC1wKCbyGhcmZAOWESqlfxahT43g947A8WogYDrLSE8HdJTeV8vfIjw3kde4NHb8vreksTD++TswXoidlkS5VKfqX9XRiaXpe0PT5wQ/9zcp4AzSVcL2VJByfrtkwntU2BAkMuaNUtzU/MzPoCUdoeKmW0msYmI/lgiPkoseopTbJgvbob2ABnY6gzO7oYoGFtoLyMJ2KOW2kYseSoRHTezHEtsa8i0TAKA8cCveCDbVepzogwr3Si4apJz3GljUe1R1dsP7hgDlvJdcNKhwb5zogzbVujdCeaA15FsqwKHo3HRLrDt2b4pf23lTsnPPuK/W8KZRzc1qGMFXayQ794zHr+28SXfs3tS56Zam9vmPQkuS4Ay2/XRz4/gaPY+p1xZnCFa3S5TJiiNAZp0PBairp1qvZ4ZrI6unRgb/x0crPpAkafmMtczeFnMxUyj7iKkl9c9g3JcwZlUqRMos1/4hQ4FUiDBmFcZ9qZbUP7OPmCmULebilgnQkl1gs5zPBFNkJbCK9oLclcFcXiawRYJD6rq5IUEZJ2aUOJ3CPwp6syCDVY3TPBku0GeP2/eWLQGPotCbovfnseeVCGwBh+HXnaK5wgCFRiltIV41QdJukes9urNVfh9XBDwln0NRasQ47DKLrM1iV5YIinka674ViFEmSBgjHq+SPpmidyekWyMCBOEifb5p23PqBxyKn8h5+OmCxiBnBJhrQ8yflwgyDfLmYD/gsKF65O9Fjvi9RWYaolGCflrBeNgVo7sE5SpZzL/xq6Z4NDVFz8pyJokRjAN6Qb+dwXyhRECJ4GD39uiyC+IcEjT01zhFk+Qja4cUbXSCiZnCPwZyIzCo+CRHwPn63Jy5HG8OWKzov+Sw55YIaKz5j9juVLHlIvaEDlxXGYBk3yjp+x+QDo0do4wGg1CcDnsh/vwkabsg19FohjaFpgTIAGPoWQH69Sz23AIulztYzR+jnhfBVIqY3gq2q22HWVB+BMAac4UaOcWj+A/GDz57ZBEgh8WjOYVzp0j/MUG/k4GXPzEBauqX5rF/KchlBXHkDvbtjwL1YC2mlMP2VDAdxR0UMw8Hn/6dBwHSyV+qSYtXWtVTvPf4sUlIU5AjH1MsQq7Rjs+p6mUhMlTD14Dtn4gAgbGXRcgVTgw5bz50aXFEGMGUstjeitru8rhkwu8p+q/p7uG9AIquk3w0aW35G159UQdV/OhEIxKOpCe/vnwRKyTqr/DoEP4TEqAjyocShYFEDj80jh6rBaaK7SgS9HRhu9vGCexajAwgsv/gMyL7MfJDAjfsFnTcLWJKsdlHOjR+TLvGWUqVNrSWBFqrh1TnzqWpo3BQyG8MezoHwt4u3KIOiAJUP1zteW0cjUyliO3tQirFt4iCOwjsQLTx9l3i1S+4bw0L7luDePXRxtt3EdgBouAOqRTfsr1dmEoRZdrWhypGD1GAW9RB2NtF2NM5EBTyG5vh0tQ2uPu+jUHt6f++wE/Wvu4PTH0ueW+/S/aN4mt1BEFRxBpMKU/Q142tFN8w+czDau39rlbbRxTS98SHe/fvrv4W1OokUdQlaXq9n5i6Mh0aPzV+dy9+bAJN/UHbJgpxXWVcT2diCpnnTS76TtT/+5sXfnnVnCvGpg5C133Q5YMTF72ttfrrJgrPkMB1qlerE1PoTLYvFwj6ujTobh83uegeCd0DxOmQWsvigdsPs3nv/z7P3/3u+Yj3kxK518Qab6LwbJwJfS0WrTW4ibW4hR0EPZ112158VUL3Ndfd8WJ189bkn957ac5cmq4Ge77/lRSRbWpYI225F1xvBXtCB2rAtOUJ+rpw3W3jBOYGRH4kzgzP1rY4M4zIjwjMDa67bTzo68K05VFD4/zQW0Haci+oYQ0i23q+/5Wm/5TU9GF95yXfROsJmnMBU8n5WHMtyJ/4ag0JHBLYHaR+HUYelsGhvbK4m8VPzO7Kaufqb6E796K9lW68Xok1azROT9E4wWQjQB8n9Q+Qcc/KZBJL6I4YVR+rAADvrLwFVWX/Tx41C66+doWEwfUSBSdqko5qLf5psnf4AWPMMCKcuHFuDr6z6puNWyLv2113+7USBX8kzpa1Fr+j9fj+PesfeKbzjy/3IsKJT97ZNIeWlGs7PnsDu1/8D+m76vqFbkH7cl+t/7L6i52/cLmoSppy0tPfbsruW/03grUkk7Vs9rTFp5ls+Klkz/Bz7/74/t0LP/tnesqL3z1u31vWETp9/XpFdY+IPC4i22qDe5vYlY+M2uDeqohsE5HHUd1z+vr1LbpxaeFfZd9csRa3qILrLOOrNeL3hjhp4I6W2H7rklsJeiqYbESyf5Rk1xAnP3N3q1yfxzzmMY95zGMe85jHbyX+Dw8vufCoAIF+AAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDExLTA0LTExVDA5OjEyOjU5LTA3OjAwee/5OQAAACV0RVh0ZGF0ZTptb2RpZnkAMjAxMS0wNC0xMVQwOToxMjo1OS0wNzowMAiyQYUAAAAZdEVYdFNvZnR3YXJlAEFkb2JlIEltYWdlUmVhZHlxyWU8AAAAAElFTkSuQmCC"
#define kSHARE_ICON_LINK                @"iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAADB2lUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4KPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNC4xLWMwMzcgNDYuMjgyNjk2LCBNb24gQXByIDAyIDIwMDcgMTg6MzY6NDIgICAgICAgICI+CiA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPgogIDxyZGY6RGVzY3JpcHRpb24gcmRmOmFib3V0PSIiCiAgICB4bWxuczppbGx1c3RyYXRvcj0iaHR0cDovL25zLmFkb2JlLmNvbS9pbGx1c3RyYXRvci8xLjAvIgogICAgeG1sbnM6ZGM9Imh0dHA6Ly9wdXJsLm9yZy9kYy9lbGVtZW50cy8xLjEvIgogICAgeG1sbnM6eGFwPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvIgogICBpbGx1c3RyYXRvcjpTdGFydHVwUHJvZmlsZT0iUHJpbnQiCiAgIHhhcDpNZXRhZGF0YURhdGU9IjIwMDctMDYtMDhUMTE6MzI6MTUrMDE6MDAiPgogICA8ZGM6ZGVzY3JpcHRpb24+CiAgICA8cmRmOkFsdD4KICAgICA8cmRmOmxpIHhtbDpsYW5nPSJ4LWRlZmF1bHQiPnNtYWxsIHZlcnNpb24gb2YgdGhlIHNoYXJlIGljb24gcmFzdGVyaXplZCBieSBqb25hc0Byb2duZW1lZGlhLm5vPC9yZGY6bGk+CiAgICA8L3JkZjpBbHQ+CiAgIDwvZGM6ZGVzY3JpcHRpb24+CiAgPC9yZGY6RGVzY3JpcHRpb24+CiA8L3JkZjpSREY+CjwveDp4bXBtZXRhPgo8P3hwYWNrZXQgZW5kPSJyIj8+9UL/ugAAABl0RVh0U29mdHdhcmUAQWRvYmUgSW1hZ2VSZWFkeXHJZTwAABMVSURBVHja7J1/cBTVHcC/b/eSO0kuJASQBJFQmwAKqAmlYltCq844hgrptCVtx45OiZ060xFqO9VWEemMf7QdwY4/SqOVltbi1BqgMJ3+ogRb0VoCooSSiKIgoQTMr0OSy91u3/ft7t3e3W5u73bvbi/3vs5j9/b2LjGf7/u+7/f7vu8tAQdlxh0LyulhOW3X0dZIW43auKQvJ9XWQdth2vad3fbWgFNfThwCfyc9rKRtFeeVFdlB206qCFtzpgBqb19L2720lce/X1RKwOMH8PgIFFdwYulIsB8gNCJDaBhgLCAb3YKW4HHaNqdrFUia8DcYgfdNI+CbisAJiD4O0EkJj6BCyDBynrY+2VARqBJsyKgCUPA4tj+njvFMBA/AZVUESmYJptBHhghIIQJjH5HITyW634DE/SaExP52ab9v8LOM7k/5HpPPxP58Yvq5mFNiQIRI7CgLkqkyXDwlwaVemf5dY95CH+EuqgiHHVcACh/N/Sb9tZJZBErnCEwJYkzXRQIfXRAYeGwaEDyycwIx14xfE9P3I9cg9j1L32vlM0bXx7uW8J0kek2vCwbfk3BP3P2oBLIg0xYGmcT2fIQfeFeiypBgEdZRJdjsmAJQ+Njr79SP75OvJuyol+H/CTB0RmAKMC44Dt8S/Ph7UAEkqgjY9IL+wWCXHO8nbKVKcJctBVAdvXY1tIv0+rJaIQF8//sChEctgOPw04KvH15QEcKoCCRWEYZ6EqzBPtqax3MQhSQKEgO/fL4QA380QODMEQ/0dYscfpbgs6NMIyzJA0VSETvXBNkgI50sV302UxGTmP1VmqM35TqBefmaDH4gwP+6PBAaJeMC4PCdha9/H3+qqCLU/IMivzI0Bz+kfoPiQ84rvXZ6TeDIuZ2WFUB1+O7XXiP84vLob3DuuAiDp8SkADj8zMHXD+AC+49GWkQh7imhFmISdcDPRYaD66gSDFIleDWpD6CGeof0Zh/DPM3rPHvUAyODhMN3CXz9PRL9b4yMgYYdw8SBYzGh5PXxIaKRD/Cc3uHT4Gs9n8N3J3zNEnjkoshrJT9DDNkaDgFqhq9FC/UqFgkx8C/2CRy+S+ErjoDiIBLdcOCtJDDaR61DUEFMhwJCh4J9CV+nhnzvaundqUuESJyPDt+FE3zMdzt8WQbF/NN/QkIoki/A/MD5f0v6tPEcLTTUDwFrNfhoNjT4GOpx+PkFH8/FkCcSIiJL3VCgTeJFfQC199+rhXyY3tXkwjscfr7B145CKJqjj0vZ3xvvBK7Sej86DtqNmOFDp4/Dzz/4yqwRDQ7DYsyknWYF1BqOiAKsjHr+0d6P6V0OPz/ha6/JmAhGbDXmRDX//dp8fsVCIdL7z/eIHL5D8Kv8VVBNWyAYgO4Pu7MCX3stFYcAPIpD2P+mpK8nqPDoc/1YzBGZWDgjcPg24K+Y1wQN1Q201TP48TIcHIZDvZ3Q8V4H7H9vP3udCfjsGBQjCoCMdQqw3KMv7sBKHm0+n0/ppg7f7/XDVxe1QMvC1ex8PPEX+2HZ7EbWUPb07IFnD7VBb6DXUfjsXCJKE+QIYy1FLJZeO/1helKDoULpbOXN4bMijA4RDj8F+MvnNMKW25+CpVcuBa/Hm3LJV11lHTTVNkEwHISjfW85B1/9DBEwNpSZM6hLDAEqAGb/yjFjpM32DZwSIRTklTxW4d/3qXWspQNeL8WiF264Yin1Faph//sdjsEHzSEsVpJBwSEZQoFoGFjDZpB8UZXjZVzW4W/43Hr4yqIWcFJu+3gT/GrlNsfgs2tj0QhAx7pGiI7/HH6q8O/+RCusmNsEmZDaKXXw4KfXOwJfOcogh0kMa8PZQKze5fCTw0fv/u7FayCTchv1CVZf0+IIfCUxRJKXhGHpNoefPNRD058NWVO/BmaUVtmGz+6xogDjw+bwUT5Pzb5RbJ8JKaXhYmt9q234miOYXAE4/KRJHhz7sylNdU1MEezAl2Xj7xYM+XP4pvDrptZlrffrpbFmmW34shUFSD4MFHZuHxM+uZDGmkZ78FMZAjh884mdeur950Ia1J/rJHzTIYDDN5/Vq86B+WdzB16/LfiRfIJlC8DhG95flSMF0OYL0oVv5gRY8AE4/Pjl6LmS0uLStOFbjgI4fPP7cQo3l3JmqDd9+CYK4OHwk8PH8bdloTLPn2sFSBe+bGIFPMYWgMMnao9v0Qo8XND77cC3bAHAShHoBIdf5nUPeE3+c7rTFnzZsgIUMHw09V9BU7/IPeCjCnDQPnwrQ4ARiEKAj/P6dy9uzWmYZybDo8Ow8+huW/DlVIaAQqvedSt4TX57aLt9+HIKTmChTOnirJ6bwWu9/zed2+3DhxR9gIkKP1/Aa/LQnzfC0Miwffip5AEmIvzPz8sv8CjY8/e+3eEIfLNkkPEQMIHg356H4FHQ6fvxvscchS9bdgInAPyGmfXwyE3rMw4+EBxmS7uWzV7GqnackKcPtLGWafjjW4AswPf7/HBTbSPMu7wO5k2vM4x9j/d1syTIcDBgCT6C/ybt8XjMNPgXjr5A23bmqGEZ99ob1kF9Vfo/F7N9OOa/fuqg8/BNhgBcHcwuV9YrW8FdOi/CpQtiRuEvmd0AdyxuYfCtyq6uPfDz19qgFydEDOAvRvBLsgS+SwEfoODj6/ZxeRfOG7Cp2xTAY4/f1bXbGW/fpG7AVxEGL23BARkudEomCkDhoxJkAv7MyVXwaNPD8Ikr04e069ge+On+TQwEyuIrcgA+OJx0xU4tVYAGag0a5zRGlobrgWNDy/aPEx3w33PHnYnzx4GPYl0BaHMa/qqFK+CBm9clXTVrNTb+6cub4Pb5K7IPXvdHdWrFTjbg4znC902JVQDzuQCH4T/a5NxCClSiR25en50xvksHPo/hW3YC3Q4/G6Kt1T97sTf2jXyGb3c2MB346N3nE3z9Jg1Or8/PNfzUE0EOePv5Aj9+d46JCt96IsgB+M3U9BvF9m4GX2jwjX0AcCbJc8+nW90NvlMF7/CGTK6Fn8oQYBc+Jngw5ncj+Gco+LNajy8g+NZTwQ7k9j9X1+gq8J29nfCj/RsV5y7e1BUKfMs+ANif2HHL2I/gscfjMVObMOYLfOv1AA7M6uVaAWLA6yeQChi+WS7Ak/JMYBL4uR7779n9Leg82xn7/8PhW18dnEo4aKQoMydX57b3c/iG8M2cQMFJ+CTHiycT/h84/KSLQwSn4b9++mDOmEcmbTh8S/ANFSBZIshKGRdO1+ZCsCTrocb1UF1axeFbgG86BNit4Tve15MzK4AVOS+t3gEPLlsPVaoicPipOIEOFHDuPbEv5y4AU4Qv74CHPhNVhEKGbxYJCFYSQalW7/7jxH7X+IK43eofvkQtAlWEGSVVBQ3fyAho28XDpCoCoo+AHBRAGhNslW4HRgNQXVYNc6e5ZzYQq3Zx390qfzX0nO+mfkqgsODTVlwqsxYeUR4ray0KSBG+dm3La22unAnEoaG9ZQesW7ouUsdfCPDN/IAECyChBQgKthdtKHX8hFXtulEWTF8AX7i6GbyiF46f74HRUHCCw5ctWgBwbsXOln+30T9uN7hVcBOI1sVrYNfX2tnysZj9eCcYfOuZQIeXa93dfg90u1gJmCJ4/VQB1sAf72hnawzY0DDR4Ft2AsfGcQJThI+vx6Qg/OXtv8GNV94AlZMqXa0I+MwfXGH0xYXNUEzPj5/DoWF0wsD3UvPv9ccOAYYKIIcER+Br50GqBH+lSuD1FMPCyxfYBvXsoWdory2FyssqM6cI1Hf50qJm9iCn/1JFCFIfIa97Pi4M8ScqQMLKoPBFEcIfiRnbmWNxdT204uLNNDZdji/iRI/+G9e3xiZ6MiBsl46D22EbbaabNcQBwJqIm+c2snWQOEU+szz6O34w0AunaXvt3YPwl2Md0NXbnXH4bKirkmhLsjQM4UsfiRmBrz+fO7WObcyE26CPt4S750I3m+LFpVlm1bv4lK1sKMKZwV548l9tsOPN3abwmxetgK8vaYH5l1vPgaAyPP73Nnjx4O6Mwcf3y6otKADCRyXI5oOU0QmrraxNeKgygk9lVg+zfmvqM68IH6Ai/JMqwpEoMOzxD9zyHdrj0w97T/f3wndf3AgH3jnoOHyUMrQA1VYU4JKY10/RxqGhtSHzu4KgIjzxsrKRww9uWcf2O3BCNv+tDTb9tc1R+PjaTy1AWVIFuKQOARPgEer4rB23bwFnJr+nw8F9L2x0DD4bAmYmKkBiFBBSooB8h4/H7vM98Pwb29la/LppdY4sTc+WXFNdB2XUouw7fsAR+Cy6wSigLFkYiCFgWMh7+PrXmOp9/vB29qVzp9bafsZvtqR+9gI4eqYbTpx7zzZ8MwUYpyh0YsDX5/Zxi5mmrc3w81efyVnVUqqyafV6ZgnswjerCkqwANj75bA44eBrn8FJH9ya5fdHXmLn6L272SJ4i7wwOhaEA2932obvK7NkAciEha/P7aMFwI2Zbm1bBU+/0uZqi7BmWYv9nm91LgBUH2Aiw9d/Bq3A66c64YXD7Szdi5tauM0ioBU41d8LR08ftwXfR30AX5mVgpACga//zPDIMEvu3PL0KnbE126SG6+qt9fzU31uYCHB17/GXP+TL7fBTU+tUpI8LpGlH29wHP64UUAhwtd/Hi3AE/upIjyxEtrf2J1zBZg1pcoW/NQfG1fA8PXXcaLm/l0b4bM/Wwkv5VgRZlVU2YNv+fHxHH7CdZzC/f6OjTm2AtW24Ft/ejiHb3m//WzK4KVhR+FbGwI4/ARLkCt563R3+vBTXRzK4YNhlc7pHCkA6/0Owzf3ATh80xo+LOPKhbzS02kffqprAzn8xPuwhi8X8qc39tmCn1IYyOGDaSUOFnDmYhj40xsdjsMfPxHE4ZtW4mABZzZl+6u7mQ/gNPzU5wI4fHYNq3exgDNbzt9P9vzCPnzLeQAicfgWFm1g9W425Cd72uD9C72OwC8uka1nAjn88e/B0m2s3s206d+y93eO9fwin3ImjRkoQLBfvV+QOPwk8LUjlm5j9W6mkj7f/vUjzpl9OWoBQoFYBTjJLo5EP4lKwOGDpeVaWLr97MvbHe/5n330a47Cv6w8+qaO9cmoAuifi4RWgMO3vFZvw67H4BtbvwdDl+wVkaDD9+CLjzne81EmVUpRBYj+miexJGwOPVkuBbEsTADBo0AVZJHDT2GhJpZubzvQzgo4r5lZx8q4Uu313/zlD2Fv1wHH4aNMq5UYWywHGz4RUYZf4cqgVfSkHV+VzxfgsiqFpCdUDEQmHH6aCzW/vGQFK+PCSh4s5jDq7ZjexQwfJnkcifNN4OPYf0VDiJ1jLeDAsYgCNKMClNMT5gL6phGoWKj4hYIkgkfycPhpwNd+uP5+LObA+XwE7dSsnhX4eDq9Lgz+GQr0/jclGOmL3FDB8FElQAuAlgCm3yiC6FPDhrBiBTh8cHyhZrbge7wyzP6k0vvR/J97Jay9vePstreatTBwp3b14qmosxAWwhx+HsPHf6bMjvLUs9WYRzBSK4DDQDk6CtOoFRBU618kFVGHUODw8xA+hn7V1yq9X6KHPtr7JeXlAO39FfGZwMe1GwPv6kIGEuLw8xA+SuVVEXPPmKrwI6zjFWAzaoZiKmQYC6gwiKwoAYefV/CnUvi4KxgKskSmqgyorGMVgJqEAb1mDHZFvzlMqOkgYQ4/T+Cjxz/5iqgV17NExirreLcu4gscoofr8LxkFoGy2qiRKJapP4A6w+G7Fn7JVAlmXBPtrEM9kr73H6bwr09WEHJX1GuUI4sImSkhY0BtAYfvYvjT50bhIzsd/Bi2mojxFwJHzp0tvXb6ID29FV+PnJehqJSAp0QxFhKR2AJyQiMDDt9dZv/y+WEgapfGZM/A0Ziwbx3t/TuSKoCqBK9SJajRhoLghzJ4JsUqgcyyhQKH7xKHr/JjUdgIf/AYZRS9tJXCf8CI9bgPetNnCOPnCtiHZQJCyKPsKcTh5yTOr9R5+wa5/kjGz4yxJ8kklTZmMCXALx4LRB1DDBHDRWPU7IhAxkS8wOFnKb2LGT4tv2/i8DH4RuO+ZQugswTP0cOd2mv0CSZfTdgxRkJUCYIixo0cfoZm9SbPTASPcT6GelruRmf270rG1vKzPqkSrKWHTfprGCaWzhEiaeOISLhPvAhySN19nMO3VcmDxRwlldQP88UWdWpZ27herzl8m61wTelhr1QJ0Cl8TnMOWRxJ4aNfUDJLiMwixgvbe5AqrUwtQ+QPov/jJPmDWDaPSe5J+hmLTleyey3dP87nsKeLHhl8k42L+nFWDyd2cLzXpXdZnI8mn8I/bJVpWk/7pYqwgR7uRb9Qfx3rCXxTCRRXEFNl4JKeIPRgv8zCct18vj69ixm+Dal+b9qPe1YLSdYaKYLmJ3j81GHxoUJwgOkIVmpjASfW8MWN7zHgMbevT+9mRQHilAEdxJX6kJFLRgW9+50U+la7X+ToA99Vq7Bc9REaaatRG5f05aTaOtQxfl+6vd1I/i/AAGVNrv1vEuK8AAAAAElFTkSuQmCC"
#define kFACEBOOK_ICON_LINK             @"iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAEsUlEQVR42u3cT2wUVRzA8cGUxD8Hg38QgRhjlCiBlnZ3Z+dt0tAYBCtNy/6ZmRW5GZuoB6MXLySNiQErpmDL7sx740mNJw940YM1JGLUC2kgejIEDxAFEzWhIIVS/Q0kBstCsqW4O8z3Jd9u26TTvpnPzuzOTGqpgbFVjh+8oPxwmNJT3gt3bNj+/hNWrljfqHxztOCb05SiqvqHvBtWLPnwTKEanZT+pvQkT/pf4r0AAAAAAAAAAACsFACwYgBAACAAEAAIAAQAAgABgABAACAAEAAIAAQAAgABgABAACAAEAAIALfFSrkonVN+9Kc8/ibf+/WG+eZ36TwAEjf5aE5VzQXn8kY2x+TrI8oz3zq+npQOyOcfOq6uK1/vvVGOZz6VZRwHQJI2vB/NyORP5T09lXf1hCqFL2bdD+zHMu/ca1nWEquJkS2ZTYLlCwAkYcLV6JJsrPOOGx7JueFrj2zdvcy6yQGAJOXrMwUv/Kjg1jZYfQc7rEUYAEhIclyfll3+/p5i7SkrM7zUWqQBgGRMdM7xwo97SnVnMTc+AJLz7P/R9qLnHx7Qd1uLPACQgOJdf6asn7RuwQBAu+eZP2xXb+/cvOceAKQQgBz7v1NuYFu3aACg3QHEZ/Pc2uMASCkA2w3fWDe476EFbt8lj/aN3GkXd92fc2srutxgVZy6qnwlqMqLzIMAaNNylbC0oON/30hHoRgsV8X6RqesX5cVtSvv6wl53C+Hldq/ufqAqkY/A6Bd9wDF4OmFvPfPFoN1jmcCxzczXA5OcJdP/jR5gScesmJejS8YxRePAJDUCcYXfnzd0+zGV2rsLlk5b8nGn+WGkEQD0GdVOehuFsD6rbuXKV+/yx1BiZ+gnl4IgO7+8QflBd4YAFIKoHOzvPp39V4AAAAAaQQQnzhSfrgPAAAAQAImcVberp2UfromTx+Vua1tFsCagfceyHnhzobLvCZzQlXNNABad7PH9/lK7RW7ON41v8zQxPrV8p6++dPAfR3dg6MrGy1zfk659pLj6UMAaN0kvsy54bNWi0a+Eg45vvkaAGkFICtQDgVTAEgpAMfVL8sh4BgA0gqgGr5Z8PVpAKR2DxC+LX/DXwBIIYD4bqH4fIG8DbwEgBQCiE8YOX4UcSIopQC6tpk1yos+AUBKAWS3Bbbjmc8A0Nrz/ZPZSr3fskbuaNzNjOst80p2OdiiPPMVAFp6KtgcypXrOzr7R1fPr3twYmUmo5cuZMPH/yyi0TKvLl8KhwXAYQC0+n/6VM05+fzM/JSnT9l+2NX8/QB7lsuufbTRMv+z/Cu/dxYAt+XlYMPlYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAID/AcBFx9PfOL75vKnccFJ+9jgAEj/BaE4meUEeZ5rPzAKAAEAAIAAQAAgABAACAAGAAEAAIAAQAAgABAACAAGAAEAAIAAQAAgABAACAAGAAEBtDMCu1Hvli8PSCUpVU7lKWLLUlrH7eobGe7Ol+iZKTz1D9d61z9VW/AMYHoNJhbR/GwAAAABJRU5ErkJggg=="
#define kTWITTER_ICON_LINK              @"iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAIfklEQVR42u1dCWwWVRCmKogXAaKYeOAZjUI8421ivJVIPCDGaExQoxiPKCrGqAneMWo0ouAV0eAVxZZy3wgUytVCKaVcLaVcpRRK/2P//ff4O75vCU1LC+3ff4/3dmeSLyEUtm93vvfezLx5Mz16TIoRI8Lgj8AE4I/ABGAwARhMAAYTgMEEYDABGEwABhOAwQRgMAEYTAAGE4DBBGAwARhMAAYTgMEEYDABGEwABhOAwQSIJs6YGqchRRqNKtPpyy0G/bTNpInbTfqh2qCPKtP09OoUXTMvScf/ywQIDS6YmaAxG9K0rsmmZuqaxMxm+nunSQ8u01wngyvPY8V2jqvFTC7YZXVZ6UeTHVqGXl6rU6/83MZz5dxD4zl1cpwJ4CX6TYnTj9uMnBV/pFQlMnTXYi3r8VwliPiPWE0wngk1ppxbAF7sgaWa8sq/eWHSmbFeylfCdujZyWqAnw9fnqKF+6yW/wcCDJqTkJMAKw/YlLSanWVTVeU/sTJFpre6bxEotk9h26X8BLG33yEm0vgqgxrS7defP2pNOY3AW/9Ltgxyd6qZzp+ZUE75I0t115f8zqSk0abbFiUdj6Jwt0VN5tFHEBeT6+zpcTkJ8Ktwg1pLdTJDZ7k5WI+BpTbjt/azlKeEeymlG4hlqyPmVsYydOY0+UlwudhTNVtu7f9cY8obB7hlYfKoA98cz9C5M+TdDmBorY9lpFb+7L1WpwZjoAQYXa4f8wW2C4v6ktlykuCt9WmplT+rzqKTCtqPG8YjbJZXhe0QOAF+qTE7fZEDRrNj7Mik/P7C109Y8i7931W3dRX7CqU/tiJFk3aalLKJtiYydFouASG3PuSCeqtLL2RkPDBkcsB7G+Sc/Zgsjwt39KJZCRpWnKLPNhm0QrjYrc0UXRAgZ3fbrQ+55qCd1QsiwnZifrDKRyx9jy7n7K8X/r/eyScFQaSxAcqbsjeiSgVpLg3QLrh3iUaqyrsVabmMwNWNdrdeBPvYS2t1yguAAF9vNZRU/lgxbum8ALgpuYZE/fYScKyrmoyrMtydLG49CNZqrpIWu8j7wijryOXxwve3mtVS/qeb0vLGAV5co7v2ortSzU5GzXEeZtNgtVFFYPnj+0qdEYSzarelIpZxLF0v0qqOFbmUSXAaeOdiD4/X3XoQ9qU6j1wqBDueL9XplMnxSHkAiJ6eM91ju8jNh4312KrGYRMs98EuJEPcXyQ/ARD4USopFIrxS2DBv7FOpwu7mXPQOndBVkGcRLms4Bl1lu8faoOwFWAhIx3t5IKubRPI8GUCeEAAxKaDTKpAKheWzm/EVvFMyaHc/I5sBxiWus1bgCdZwd9WyRdhQ2x9ufigOEVDzOLDyjTt1eUOBCxuUJQAmHFIAmHJTabtsdS9GQSDMK5aqE0yQY6l0lfDEMDQbVZkd+WLzYY6BCjeb9Mjxe2jdncv0aTOuJFZXinT1SFAo3FIyTtTGSd7BX724VSmK+YmaVuSbYJs5eFiTR0CbOrA6MNZ/6pG27nJguvTaeZAVjJ4TkIdAgQRAAqz4ASwlx8pc249CEURWNwTuNFKFYi4r0hjrbkorl4A9YMAyPBla18xD8DtOMDE7SZrziW5bn5SPQLcpEiWjeyCukK+FZdy+4GtK1mwSHwG4BUBrl+QlP6OveyC9Dely8TJeBysknieB+g1AZCVUxHjsF93BDesQlEoEnn3+w3eC7KV19bp4SAAcIOwB2Imk6CrAtvJ95pKXv+Ca4U/W59mEnRFZtZZ/irfr0qhqA+E+oEsxxbUEw5tsWhUEXt7fdo5ImZpL6hKGkhlcb9/IVwczg1oL6/7bfwFXSx6wNS4c7MHbk/ULQQYykeWiw0VAXBzGFe4ehe0vZ8P2wCJo7jVE2Vv4YPKNAU1EX0hwJhWlbhwYmzw8t8iuPDatzAebgIMFDOdUwU6lncqApz9ftoAv9dyrsCRUiss/94FsWgQALdxeelvK67U+VPJC5C1KmcQMq/eCl75fhMAlv+qRo4E4brcxbMS0SPAYYMw6mcDgQV9ZAkEoWhDVP3+RftsT8vfKRMJxClhQ8RWAtyfPE+2xhlB/nI0lSprioZNAKpL2U4v6AHgQsnnmw2yQ74YfLwxLZ/yZeocipuwSIcOo6DNa56MypexdSxqCSCreF9I7AM00nCzwmlkuofDUr5xQdJxmX6rNWnZfpu2JDJKlZzBDV8ce3P7eJdqEYMMpiLhZMT5B85QoHOqCspHq9S5e9WxD2qSGXXa5so8OGwDL6zRlQoaobK5EjNfdgLcvkijtQfVihGgtOvpU9XplSwlAdBYcn69eu5g/i7Tl1Y3oSQAkiKeXJVS8qQQt3mQ1ZM3SUHlB0kAHA3fs0RzGkgeVPRgCKeaqI3UQ1Xl+0kAhHxR9mRUmU6Fuy3l6wijLN4A1fZ7NwmAdG7cZB2xOkXDl6do6FKNHlqm0aPiz8+W6PRmue60d5kslI2GDmFJCkVP3xES9T4OdAWAsnGlKSqneYhIhmLWu7kFwPKFEdQU4gQPFMJG6ZtQKd5tG6D/lDh9sjEdqh4BJcIrGbpUC6fivTIC+wki4BYwun+qKgg7DykKueK99gLg5sE4xMdUoWoY0tPQ9/CyOYloKN5PNxBXwkcLr0C2QA/slr92mE5hhp75sWgpPsj6AM+V6k7o1O8iUkg7w3V0tGJBj8HIKl2WUDDCp4PEkotO4eOrDCpqsFs6j+QqqESCUnV/ihmOmARa1/QpjLPCVTgNhEeBtHEszSPFagE3E21oxgmSIHQ8ocak76sNJ9CEv8fP8e+GFaecruCotJXHyg1XRhCDCcBgAjCYAAwmAIMJwGACMJgADCYAgwnAYAIwmAAMJgCDCcBgAjCYAAwmAIMJwGACMJgADCYAgwnAYAIwOsL/hxf9TJJ6RE8AAAAASUVORK5CYII="
#define kGOOGLEPLUS_ICON_LINK           @"iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAALKUlEQVR42u1d+XcURRD271F83nhfIJdBARXRKIKi8EDwREFQRBQVVERU8EAUlUtEo0gE8QAUDwTJfSfkvpPdbG522Xa+zkMDb2e3u3e6d2an+r36LS870/1Nd3XVV1+dkzPqXEbmXzuHJoEAQBNBACAjAJARAMgIAGQEADICABkBgIwAQEYAICMAkBEAvGi5N53Pcsfot5zR5xEATFvBbdewykUPsYb1q1j7t9tZ6K9DrL+ylJ1sb2WnBvoZi0aZ9hE9xdqytrL8iSMJACYWvOaVxaxzXxYbbKpnqR79VaWsbP7ddATotPxbL2d1a1ewnryj/Gtzw8Du0vjBG0NbP/kAeqzk/ltYR/auoa3cRSP092FWdM9YcgJ1WfGMDBY4sDfh+X2qv49FekLGFj4c6GA1K5+mW4Auy7v5Eta6YxOLhsMxFyDSHWLt32xjlYvnsILJV/3v5Y+9gBXfdzOrW7OcdR/7Q3mB8dsnnltgY/NZ/qQr6Rqoy8oXZLLBhlrb87Zp0zqWl3Gp0P8qfWgK6845Iu/Mnxxk1S8tpDiAaat/5xUWjURie9nWla54+gT5/2vdyevfXmn7f+1REOUOJwHAhFmL1PbV57Zr0VuSn/TduvLpB+WdSAsEta8vIwDoNgRP7AYCOQW3X+vI71Qumm3rV9jHdiLc1yAAaDKc6fEGHC8nf6/uzRekfQLcMIoyxxIAnLaqJXPjXvF6Co9r+d3AL9nSIOjJP+b5GL+rAFA49XoW7grEnXRdd+2CKVcn/O1Ywy/+gBEABA/ui3/2Wmd13sTLtP1+3Zrn5QNAHW0sb8LFBIBkreLxGYm3XE3b/39BozHns4H6GmkQ+OFqqB0APQXHE040In26n6N21RKlrB8BIJlI3yP3CE104/uv6yeIjLuQx/VlR8msyQQAVev8cbeYw7V6qZGXbdn6oTQAkP4lAKgkeSwHSjQaV/2imVh8yaxJ0gDoOvwzAUDp3r90nvAkg+1j6oUHaqqkADDY0kgAULHWnZvFve01y429cOvOT6TDw+nEADIGAETTREfTx28be2GQSWVHwR3XEQBkLRzsFJ7g9u92muMa3nK5NGu46N5xBACpK9f4i+Ri73lHjb70QK2cH5COXECtAEBKVyoD1x0ymnwJHtovdwQ4lKL2DwCsM1N2FM/MMPbSLds2ijuBkYgFzhEEAKlzduJI+bj7mucN0tFeFr8GNtbRNVCF9hUdHJACQPDX/cZeumblU+LPdfAHAoCK9VdXyFXd9PUaS7+CeSQ6QDJ1vAZi+nh+5J1t4C6kDQBE8wBnhIRXPGGGnfTsw8JEUR30MDuCSvPn76UPABDdUym/ctMR0JP7t54YiR8AUDjtRvkybevvUSKm+6VRVi4ynCap+goAPBxsfUGyo2NflvaXbt/9RcLn6C3O0xab8A0AcKbL6y5EtMcE+qvKEj5D2dyp2n7fNwCATIsKFw/FnrqeCWHdRKN587taJ903AOBXrmWPKFXt6mIJtWyPHwXs+uOA9sifrwAAw6SqqHGUPHCr444p9AVsz/3CHF6urns+fAcAaPyEO9ulQTDYVMcKp97g2HEUOva7/eIX5XJZGhPz4TsAwMoevktJ9qW/ptL6ckclvfgd338VN/6gszCFADCsPhCCDCpVOuWPTlfOTIaOHo5LRjFN+fItADgla+EsFuntVtDli/L7O+oMRaVnUG8AroFdmrd+3UspScD4GgBDyZAJXAVESZ8xHGaBn/dwJnFR5pgzvl587dD16diz03bhOQHFAiBK1pwpfL2BO5cyFgl1xXyutl2fSf+v/ElXeFMiBiJPIIPKpo1j7Qyo6Rf9P7gFlM/PdOw9TCqWxYycZn/pbZUwOHhtX29JHgiCYIEf4uTzEwCcVAZ9YxmPAuoCA4Dm9HMTADQVcqKwFICAjl/n/m9Z8Lcf+XUNQaXAT3u41pCMPiBuHzoIFwSAFBp0BYS5Bkf1cA0IACkyqITKjPbdOwgA6QQA3OGlJmrv13qEJ1Yv5WpkMmaXj0DfA9n/lex11rMAiKc3GDOkXF3hmmf3fSDIEdKp5RjKjoqFDxAA0gUAIrSuWEUewxXHCQAeBgCkW1RGX1khT08TADwOAFEBqtg8g3ouL08A8HIcYPQIdrK1SRkE4CbUvvoMAcDLgSD0HEh2wJdA5JEA4EFDRlFW9CkmHawknxXdNZoA4EUD1Uy6Q0gs1lGw0/Ir7iUAeNEaNqx2JlscPmmkQxgBIAlyZ+GdN7KyuXfyvD7CsKB9QQEU5eVOjcaNbxIAUsoNmDiSlT92H6/NR2/g7n/+ZIPNDbxky9SAziEBwNSCT7qS1xHCI+fCEiaaP4sQSLK26gliWTsMFvtsA2HWNwAAmRHZrO7jfxn9smUHjheSiHHSa7fOb6iHSNcHRE+xgfpqLt6M7RlCTyeWP8o9d/Qbhm8Axg8MTF00pcT1zolR+9pzBIDkF35q3AKNWBQuUMAQ80fYV0U/CJTxli0fJN19HM9SOvs2AoBSZY71RYKMIXquQzUUnH8nS7Uqnryf9yRMZqCOIR1Fo7UCABIroprBIHvqFGVABhA7SjIjVZVEHtQJHCEsy47MHFq9mkogQfxB9ZaBXcR03sBzAEB8HqKPQl+95dAl2ydYqUh16Ty1+kTGjEQKPQsAROrA3xfKwkEiPoUavGgfo5JOBnGTAGBH1IzTFXz44LKwLhBgRnGlrHQ8qpbS6RhwDAAnlj8mduY3N6Rk27ev7r1eWsiqbN40AsAZHvbkq4S9/eoXHndfkcn08SwSCooHhlYtIQCobP3Ybt3alVumy1nTpnUEgOFbqGhYV3eaNVkLHNgrlincsYkAcNog8iA6Sufc4e56w5kZQjGC1i83EwBOm6gXDdoWYgRun5DunCMJ36X50/UEAC67mjlW+OuH0le6FJyAjUwAGCXXegVXLS9MCMLSiQaaTxIALMNWKB5Hb/HEhECeNtEQlapLewBAdEEmp45QsdsnBF1CE15lKRQ8ZFCnkBlg7rh9QlAzGJcitn0jAeC04ToklU/X0IHLdEAolUWlrgNAw3uvSQGgp+C46ycEUT67gSsiEUIkPeazh5MqnVqUx+K0va9cPIcAMNzyMi6VZvfyXcCl+QBoGNtFAtONB+BYJFClG0jD+lddORl2PQWgJQBZOgJArGNg0Wx5mnUkkpIqmLiKIwsybenjJhtbezId3FtSoKTQ4RbVLjCGQVSJNVDEQpVBiYo+5k1TYtqiHLtu7YrULv6Uq1lfeZGtvKwXEliuoIQ1f7ZBmW8PIqlTzaHkiKGTeblZTGfVug3AyU3nxXeWFDp6hJJD+N+R0NfLWra8n3QHDKHby4SLh5pV2Nxggof2s9zxF6X94jtPC7cmLV5rNlHfoCN7F3fKnL4uogwd6V4kpuwKUHmNvgsYy94tDBl3Ievcl+VIVS4qcZBvgJwb7uiyC4PkE/j/9W+9yO/x6Ddk+1utzY71EaLSMEi4WZOu0icwEScfRZpdfx7kuwQSM82fbmCNG9eypk/e4bX8UBQJ/vYT66soEeo8AlCA42eyb6BvikORWg0d+dWVwg8QpQj8ks2KZ2T4cuGN6gNgaxXh2pkYcDaxSwCcfl74lCiE4NrV/s02Fg50mP3arW0epeEo7FQRmiAAaJB7q3hipnWGf8SbNsdzzlQXHD4AClYgJ+eH+7ynVcLwVUI7CN4+HDt0BYN4FBpH48qGsi04lIgcoqwbncjRWby/qox/2XAIwU9EyVbp7NvTPnrnW6FIMgIAGQGAjABARgAgIwCQEQDICABkBAAyAgAZAYCMAEBGACAjAJBJ2L+NT1qcoDWWzQAAAABJRU5ErkJggg=="
#define kEMBED_ICON_LINK                @""//"http://p.bvcau.com.au/alpha2/vplayer/images/embed.png"
#define kEMAIL_ICON_LINK                @""//"http://p.bvcau.com.au/alpha2/vplayer/images/emsq.png"

@interface BMConstant : NSObject


@end